spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: false
          configuration:
            commit:
              interval:
                mms: 1000
            default:
              key:
                serde:  org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde:  org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
          group: greetings_group
          consumer:
            header-mode: raw
        greetings-out:
          destination: greetings
          contentType: application/json
          group: greetings_group
          producer:
            header-mode: raw